version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /backend
    schedule:
      interval: weekly
    groups:
      backend-npm-minor-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /electricity-prices-build
    schedule:
      interval: weekly
    groups:
      frontend-npm-minor-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
