version: '3.8'

services:
  # Main application service
  app:
    build:
      context: .
      dockerfile: Dockerfile.captain
    container_name: electricity_prices_app
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://electricity_user:electricity_password@postgres:5432/electricity_prices
      ELERING_API_URL: https://dashboard.elering.ee/api/nps/price
      FRONTEND_URL: https://your-app-name.your-domain.com
    depends_on:
      - postgres
    networks:
      - electricity_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # PostgreSQL database
  postgres:
    image: postgres:15-alpine
    container_name: electricity_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: electricity_prices
      POSTGRES_USER: electricity_user
      POSTGRES_PASSWORD: electricity_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - electricity_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U electricity_user -d electricity_prices"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  electricity_network:
    driver: bridge 